### PR TITLE
Multi-byte read

### PR DESCRIPTION
**Pull request by icypete**
Added support for reading multi-byte data.

Essentially register for enough sequential address to fill the register type.

Then read enough registers to build data.

Adjusted the masking to only be applied to uint types (I don't think masking any other types makes sense).

### CODE REVIEW

**Comment by tjhowse** [comment]
Thanks very much for doing this work! It makes me feel warm and fuzzy that A) you found my project useful, and B) you are actively helping to make it better. There are a few changes I'd like you to make to this PR to make it perfect. If you haven't been through a code review process before (or even if you have!) this can be a bit dispiriting, but I think the end result will be worth the effort.  I found this site to be a good start as a reference guide for raising high-quality pull requests: https://mtlynch.io/code-review-love/
Thanks again!

**Comment by tjhowse** [comment]
The last big thing this PR needs is some more testing to cover the new code. The most straightforward way of doing this would be adding the new types to `test_mqtt.test_type` and `test_type.yaml`. In [test_mqtt](https://github.com/tjhowse/modbus4mqtt/blob/master/tests/test_mqtt.py#L399) we define a list of dummy modbus register contents, and then we query those with a `poll()` and check what values were "published" to our mock MQTT interface based on the registers configured in `test_type.yaml`. Testing these new types would be a matter of expanding the list of dummy modbus table data, and the registers in the test YAML, to demonstrate the conversions from uint16 to whatever types work as expected.

Writing these tests strings up a safety net to catch future changes that might break the functionality this PR adds.

**Review by tjhowse — CHANGES_REQUESTED** [review]

**Comment by tjhowse** [comment]
Ah! We'll also need to update the readme with the new supported register types, and note in the `mask` row of the table that it is only supported for use with uint16 register types.

**Comment by icypete** [comment]
Thanks for the comments! I shall get on to them later this week. (I like feedback in all forms, it is how we learn :) )

**Comment by icypete** [comment]
Got a bit sidetracked on another project. Hopefully will get to this by the end of the week

**Comment by tjhowse** [comment]
No worries at all, I know how it is. :)

**Comment by iconnor** [comment]
With the pep8 changes I just made in #32, I think this would be good to merge first. If not, I am happy to make these changes after #32 if it helps.

**Comment by tjhowse** [comment]
No worries, I'll fix up this PR after #32 is merged.

**Pull request merged**
